module.exports = {
	title: "Asset Allocation Planner",
	sliderInstructions: "Select a risk profile from 1 to 10:",
	riskProfileLabel: "Currently selected:",
	chartTitle: "Ideal Asset Allocation",
	seriesName: "Percentage Allocation",
	largeCap: "Large Cap Stocks",
	midSmallCap: "Mid/Small Cap Stocks",
	international: "International Stocks",
	bonds: "Bonds",
	cash: "Cash",
	formTitle: "Current Asset Allocation",
	currency: "$",
	conservative: "Conservative",
	aggressive: "Aggressive",
	nextSteps: "Next Steps",
	nextStepsSub: "To reach ideal allocation of assets, make the following transactions:",
	move: "Move",
	from: "from",
	to: "to",
	nextStepsInstructions: "Enter your current allocation of assets in the field above.",
	noStepsText: "You have already achieved ideal allocation of assets. You do not need to take any additional steps."
};